services:
  honeypot:
    build: .
    ports:
      - '8021:21'
      - '8022:22'
      - '9080:80'
      - '8306:3306'
      - '8081:8080'
    volumes:
      - ./logs:/app/logs
    environment:
      - DISCORD_WEBHOOK_URL=
    restart: unless-stopped
